GET http://localhost:3000/api/matcha

###

# POST http://localhost:3000/api/matcha
# Content-Type: application/json

#     {
#         "name": "Activated Charcoal Matcha",
#         "price": 35,
#         "id": 5,
#     }

# ###

# PUT http://localhost:3000/api/matcha/id


# ###

# DELETE http://localhost:3000/api/matcha/id