GET http://localhost:3000/api/matchas

###

POST http://localhost:3000/api/matchas
Content-Type: application/json

{
    "name": "Activated Charcoal Matcha",
    "price": 35
}

###

PUT http://localhost:3000/api/matchas/id


###

DELETE http://localhost:3000/api/matcha/id